swagger: '2.0'
info:
  version: 1.0.0
  title: <img/src=x> booo
  description:  <textarea name="xss" title=""></textarea><script>alert('XSS')</script> <!--"-->
  paths:
    /:
      post:
        responses:
          '200':
            description: Login successful
