swagger: '2.0'
info:
  version: 1.0.0
  title: Example yaml.spec
  description: <div><xmp><b></b></xmp><img src=nope.gif bonrror="alert(document.domain)"></xmp></div>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
